$(function(){
	$("#a-info").click(function(){
		$("#a-info").addClass("list-selected");
		$("#a-password").removeClass("list-selected");
		$("#change-info").css("display","block");
		$("#change-password").css("display","none");
	});
	$("#a-password").click(function(){
		$("#a-password").addClass("list-selected");
		$("#a-info").removeClass("list-selected");
		$("#change-password").css("display","block");
		$("#change-info").css("display","none");
	});
	
	$("#a-problems").click(function(){
		$("#a-problems").addClass("list-selected");
		$("#a-contact").removeClass("list-selected");
		$("#question").css("display","block");
		$("#contact").css("display","none");
	});
	$("#a-contact").click(function(){
		$("#a-contact").addClass("list-selected");
		$("#a-problems").removeClass("list-selected");
		$("#contact").css("display","block");
		$("#question").css("display","none");
	});
	
	$("#a-pesticide").click(function(){
		$("#a-pesticide").addClass("list-selected");
		$("#a-type").removeClass("list-selected");
		$("#a-plan").removeClass("list-selected");
		$("#a-fixedinfo").removeClass("list-selected");
		$("#content-pesticide").css("display","block");
		$("#content-type").css("display","none");
		$("#content-plan").css("display","none");
		$("#content-fixedinfo").css("display","none");
	});
	$("#a-type").click(function(){
		$("#a-pesticide").removeClass("list-selected");
		$("#a-type").addClass("list-selected");
		$("#a-plan").removeClass("list-selected");
		$("#a-fixedinfo").removeClass("list-selected");
		$("#content-pesticide").css("display","none");
		$("#content-type").css("display","block");
		$("#content-plan").css("display","none");
		$("#content-fixedinfo").css("display","none");
	});
	$("#a-plan").click(function(){
		$("#a-pesticide").removeClass("list-selected");
		$("#a-type").removeClass("list-selected");
		$("#a-plan").addClass("list-selected");
		$("#a-fixedinfo").removeClass("list-selected");
		$("#content-pesticide").css("display","none");
		$("#content-type").css("display","none");
		$("#content-plan").css("display","block");
		$("#content-fixedinfo").css("display","none");
	});
	$("#a-fixedinfo").click(function(){
		$("#a-pesticide").removeClass("list-selected");
		$("#a-type").removeClass("list-selected");
		$("#a-plan").removeClass("list-selected");
		$("#a-fixedinfo").addClass("list-selected");
		$("#content-pesticide").css("display","none");
		$("#content-type").css("display","none");
		$("#content-plan").css("display","none");
		$("#content-fixedinfo").css("display","block");
	});
	
	$("#a-finished").click(function(){
		$("#a-finished").addClass("list-selected");
		$("#a-unexport").removeClass("list-selected");
		$("#a-making").removeClass("list-selected");
		$("#content-finished").css("display","block");
		$("#content-unexport").css("display","none");
		$("#content-making").css("display","none");
	});
	$("#a-unexport").click(function(){
		$("#a-finished").removeClass("list-selected");
		$("#a-unexport").addClass("list-selected");
		$("#a-making").removeClass("list-selected");
		$("#content-finished").css("display","none");
		$("#content-unexport").css("display","block");
		$("#content-making").css("display","none");
	});
	$("#a-making").click(function(){
		$("#a-finished").removeClass("list-selected");
		$("#a-unexport").removeClass("list-selected");
		$("#a-making").addClass("list-selected");
		$("#content-finished").css("display","none");
		$("#content-unexport").css("display","none");
		$("#content-making").css("display","block");
	});
})